import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync, backup } from 'node:sqlite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { PrismaClient } from '@prisma/client';
import { assignAsset, assignmentState } from '../src/services/assignment-service.js';

test('safe additive migration and assignment API service on an isolated database copy', async () => {
  const folder=await fs.mkdtemp(path.resolve('tests/assignment-test-'));
  const dbPath=path.join(folder,'test.db');
  const source=new DatabaseSync(path.resolve('prisma/dev.db'),{readOnly:true});
  await backup(source,dbPath);source.close();
  const before=new DatabaseSync(dbPath);const counts=before.prepare('SELECT COUNT(*) n FROM workstations').get();before.close();
  const url='file:'+dbPath.replaceAll('\\','/');
  const run=spawnSync(process.execPath,['scripts/migrate-direct-assignment.js'],{env:{...process.env,DATABASE_URL:url},encoding:'utf8'});
  assert.equal(run.status,0,run.stderr);console.log(run.stdout);
  const again=spawnSync(process.execPath,['scripts/migrate-direct-assignment.js'],{env:{...process.env,DATABASE_URL:url},encoding:'utf8'});
  assert.equal(again.status,0,again.stderr);
  const check=new DatabaseSync(dbPath);assert.equal(check.prepare('SELECT COUNT(*) n FROM workstations').get().n,counts.n);check.close();
  const prisma=new PrismaClient({datasources:{db:{url}}});
  const id='test-'+Date.now();
  try {
    await prisma.personnel.create({data:{id:id+'a',fullName:'Test Person A'}});
    await prisma.personnel.create({data:{id:id+'b',fullName:'Test Person B'}});
    const ws=await prisma.workstation.create({data:{workstationTag:id,status:'IN_STORE'}});
    const initial=assignmentState(ws);
    const assigned=await assignAsset(prisma,'workstation',id,{personnelId:id+'a',expectedState:initial},'test');
    assert.equal(assigned.item.personnelId,id+'a');
    const retry=await assignAsset(prisma,'workstation',id,{personnelId:id+'a',expectedState:initial},'test');
    assert.equal(retry.unchanged,true);
    assert.equal(await prisma.auditLog.count({where:{assetTag:id}}),1);
    await assert.rejects(assignAsset(prisma,'workstation',id,{personnelId:id+'b',expectedState:initial,allowReassign:true},'test'),{code:'STALE_ASSIGNMENT'});
    await assert.rejects(assignAsset(prisma,'workstation',id,{personnelId:id+'b',expectedState:assignmentState(assigned.item)},'test'),{code:'CONFIRM_REASSIGN'});
    const peripheral=await prisma.peripheral.create({data:{peripheralTag:id+'p',workstationTag:id,status:'IN_STORE'},include:{workstation:true}});
    const direct=await assignAsset(prisma,'peripheral',id+'p',{personnelId:id+'b',expectedState:assignmentState(peripheral),allowReassign:true},'test');
    assert.equal(direct.item.personnelId,id+'b');assert.equal(direct.item.workstationTag,null);
    process.env.NODE_ENV='test';process.env.DATABASE_URL=url;
    const {app}=await import('../src/server.js');
    const {prisma:apiPrisma}=await import('../src/prisma.js');
    const jwt=(await import('jsonwebtoken')).default;
    const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
    try {
      const base=`http://127.0.0.1:${server.address().port}`;
      for (const role of ['ADMIN','VIEWER']) await prisma.appUser.create({data:{email:'test-'+role,fullName:'Test',role}});
      const token=role=>jwt.sign({email:'test-'+role,role},process.env.JWT_SECRET || 'assetflow-super-secret-production-key-2026');
      const endpoint=`${base}/api/assets/workstation/${id}/assign`;
      assert.equal((await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);
      assert.equal((await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token('VIEWER')},body:'{}'})).status,403);
      const headers={Authorization:'Bearer '+token('ADMIN')};
      const people=await (await fetch(`${base}/api/personnel/${id}b`,{headers})).json();
      assert.equal(people.peripherals[0].peripheralTag,id+'p');
      const lookup=await (await fetch(`${base}/api/assets/lookup/${id}p`,{headers})).json();
      assert.equal(lookup.data.personnel.id,id+'b');assert.ok(lookup.data.assignmentState);
      const writeHeaders={...headers,'Content-Type':'application/json'};
      const patch=async body=>fetch(`${base}/api/peripherals/${id}p`,{method:'PATCH',headers:writeHeaders,body:JSON.stringify(body)});
      const toWs=await patch({workstationTag:id,personnelId:null});
      assert.equal(toWs.status,200);
      assert.equal((await toWs.json()).personnelId,null);
      const toPerson=await patch({personnelId:id+'b',workstationTag:null});
      assert.equal(toPerson.status,200);
      const personItem=await toPerson.json();
      assert.equal(personItem.personnelId,id+'b');assert.equal(personItem.status,'ASSIGNED');
      assert.equal((await patch({personnelId:id+'b',workstationTag:id})).status,400);
      const created=await fetch(`${base}/api/peripherals`,{method:'POST',headers:writeHeaders,body:JSON.stringify({peripheralTag:id+'direct',category:'Mouse',personnelId:id+'a'})});
      assert.equal(created.status,201);
      assert.equal((await created.json()).status,'ASSIGNED');
      const history=await prisma.auditLog.findMany({where:{assetTag:id+'p'}});
      assert.ok(history.some(l=>l.actionTaken.includes('assignment: Test Person B → Workstation '+id)));
      assert.ok(history.some(l=>l.actionTaken.includes('→ Test Person B; updated details')));
      const createLog=await prisma.auditLog.findFirst({where:{assetTag:id+'direct'}});
      assert.match(createLog.actionTaken,/Created peripheral; assigned to Test Person A/);
      const editWs=await fetch(`${base}/api/workstations/${id}`,{method:'PATCH',headers:writeHeaders,body:JSON.stringify({personnelId:id+'b'})});
      assert.equal(editWs.status,200);
      const wsHistory=await prisma.auditLog.findMany({where:{assetTag:id}});
      assert.ok(wsHistory.some(l=>l.actionTaken.includes('assignment: Test Person A → Test Person B')));
      await fetch(`${base}/api/workstations/${id}`,{method:'PATCH',headers:writeHeaders,body:JSON.stringify({personnelId:id+'a'})});
      await prisma.auditLog.createMany({data:Array.from({length:205},(_,i)=>({logId:id+'page'+String(i).padStart(3,'0'),timestamp:new Date('2099-01-01'),userEmail:'paging-test',actionTaken:'Paging test'}))});
      const first=await (await fetch(`${base}/api/logs?user=paging-test`,{headers})).json();
      assert.equal(first.length,200);
      const second=await (await fetch(`${base}/api/logs?user=paging-test&before=${encodeURIComponent(first.at(-1).logId)}`,{headers})).json();
      assert.equal(second.length,5);assert.equal(new Set([...first,...second].map(l=>l.logId)).size,205);
      assert.equal((await fetch(`${base}/api/logs?from=invalid`,{headers})).status,400);
    } finally {await new Promise(resolve=>server.close(resolve));await apiPrisma.$disconnect();}
    const current=await prisma.peripheral.findUnique({where:{peripheralTag:id+'p'},include:{workstation:true}});
    await assert.rejects(assignAsset(prisma,'peripheral',id+'p',{workstationTag:id,expectedState:assignmentState(current)},'test'),{code:'CONFIRM_REASSIGN'});
    const attached=await assignAsset(prisma,'peripheral',id+'p',{workstationTag:id,expectedState:assignmentState(current),allowReassign:true},'test');
    assert.equal(attached.item.workstationTag,id);assert.equal(attached.item.personnelId,null);
    const repeat=await assignAsset(prisma,'peripheral',id+'p',{workstationTag:id,expectedState:assignmentState(current),allowReassign:true},'test');
    assert.equal(repeat.unchanged,true);
    const linked=await prisma.peripheral.findUnique({where:{peripheralTag:id+'p'},include:{workstation:true}});
    const detached=await assignAsset(prisma,'peripheral',id+'p',{personnelId:id+'a',expectedState:assignmentState(linked),allowReassign:true},'test');
    assert.equal(detached.item.workstationTag,null);assert.equal(detached.item.personnelId,id+'a');
    assert.equal(detached.unchanged,false,'Selecting the inherited owner must still detach the workstation');
    await assert.rejects(assignAsset(prisma,'peripheral',id+'p',{workstationTag:id,personnelId:id+'a',expectedState:'x'},'test'),{status:400});
    await assert.rejects(assignAsset(prisma,'workstation',id,{workstationTag:id,expectedState:'x'},'test'),{status:400});
    await prisma.peripheral.update({where:{peripheralTag:id+'p'},data:{status:'RETIRED'}});
    await assert.rejects(assignAsset(prisma,'peripheral',id+'p',{personnelId:id+'a',expectedState:'x'},'test'),{status:409});
    console.log('Migration idempotency, counts, direct assignment, duplicate retry, stale state, reassignment and retired-state checks passed.');
  } finally {await prisma.$disconnect();}
});
